# Generated by Django 4.2.5 on 2025-02-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'To be started'), (1, 'In progress'), (2, 'Completed')], default=0),
        ),
    ]
